WebCrawler/WebCrawler/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
import views as v


urlpatterns = [
    url('^login/', v.login,  name='login'),
    url('^logout/', v.logout, name='logout'),
    url('^editar_dados_usuario/', v.editar_dados_usuario, name='editar_dados_usuario'),
    url('^novo_usuario/$', v.novo_usuario, name="novo_usuario"),
    url('^novo_usuario/cadastrar/', v.cadastrar_novo_usuario, name="cadastrar_novo_usuario"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^WebCrawler/', include('WebCrawlerEngine.urls', namespace='WebCrawler')),
    url(r'^$', RedirectView.as_view(url="/WebCrawler", permanent=True)),
]

WebCrawler/WebCrawlerEngine/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^$', views.index, name='index'),
    url('^iniciar/$', views.iniciar, name='iniciar'),
    url('^processamento/$', views.processamento, name='processamento'),
    url('^processamento/download/$', views.download_corpora, name='download_corpora'),
    url('^processamento/parar/$', views.parar_processamento, name='parar_processamento'),
]

WebCrawler/WebCrawlerEngine/models.py
 #-*- coding: utf-8 -*-

from django.db import models

class Document(models.Model):
    docfile = models.FileField(upload_to='%Y/%m/%d')

WebCrawler/WebCrawlerEngine/views.py
# -*- coding: utf-8 -*-
import os
from rexec import FileWrapper
from django.contrib.auth.decorators import login_required
from tweepy.error import TweepError
from controler.recursos import Recursos
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from controler.util import ler_urls_arquivo, get_tempo_execucao_formatado, get_numero_formatado, ler_dados_acesso_twitter_arquivo
from controler.crawler_factory import CrawlerFactory


def get_crawler_factory(user):
    recursos = Recursos(user.email)
    return CrawlerFactory(user.email, recursos)


def get_crawler_em_execucao(user):
    cf = get_crawler_factory(user)
    return cf.get_crawler_em_execucao()


@login_required(login_url='/login/')
def index(request):
    crawler_facade = get_crawler_em_execucao(request.user)
    if crawler_facade.processamento_em_execucao:
        return redirect('WebCrawler:processamento')

    context = {"corpus_gerado": crawler_facade.corpus_compactado_gerado,
               "user": request.user}

    return render(request, "WebCrawlerEngine/index.html", context)


def get_dominios_selecionados(dominios):
    if "Todos" in dominios:
        dominios.remove("Todos")
        return dominios
    return dominios


@login_required(login_url='/login/')
def processamento(request):
    crawler_facade = get_crawler_em_execucao(request.user)

    context = {"status_processamento": crawler_facade.status_processamento,
               "processamento_em_execucao": crawler_facade.processamento_em_execucao,
               "contagem_palavras": get_numero_formatado(str(crawler_facade.contagem_palavras)),
               "tempo_execucao": get_tempo_execucao_formatado(crawler_facade.tempo_processamento),
               "abrangencia": crawler_facade.abrangencia,
               "user": request.user}
    if crawler_facade.abrangencia == "twitter":
        context["contagem_twittes"] = get_numero_formatado(str(crawler_facade.contagem_twittes))
    else:
        context["contagem_paginas"] = get_numero_formatado(str(crawler_facade.contagem_paginas))
    return render(request, "WebCrawlerEngine/processamento.html", context)


@login_required(login_url='/login/')
def parar_processamento(request):
    crawler_facade = get_crawler_em_execucao(request.user)
    crawler_facade.parar_crawler()
    return redirect("WebCrawler:processamento", permanent=True)


@login_required(login_url='/login/')
def download_corpora(request):
    nome_arquivo = Recursos(request.user.email).nome_completo_arquivo_compactado
    wrapper = FileWrapper(file(nome_arquivo))
    response = HttpResponse(wrapper, content_type='application/x-gzip')
    response['Content-Disposition'] = 'attachment; filename= %s' % os.path.basename(nome_arquivo)
    response['Content-Length'] = os.path.getsize(nome_arquivo)
    return response


@login_required(login_url='/login/')
def iniciar(request):
    if request.method == "GET":
        return render(request, "WebCrawlerEngine/index.html", {"user": request.user})

    crawler_facade = get_crawler_em_execucao(request.user)
    if crawler_facade.processamento_em_execucao:
        return redirect("WebCrawler:processamento", permanent=True)

    cf = get_crawler_factory(request.user)
    palavras_chave = request.POST.get(u'text_palavras_chave', "").encode("utf-8").split(",")
    abrangencia = request.POST.get(u'optionsRadio_abrangencia')
    arquivo_conf_twitter = request.FILES.get(u'arquivo_dados_acesso_twitter')
    opcoes = {"ativar_ngram": bool(int(request.POST.get(u'checkbox_ativarngram', False))),
              "ativar_entidades": bool(int(request.POST.get(u'checkbox_ativarentidades', False))),
              "gerar_vocabulario":  bool(int(request.POST.get(u'checkbox_vocabulario', False))),
              "formato_saida_entidades":request.POST.get(u'formato_saida_entidades'),
              "qtd_palavras": "" if not request.POST.get(u'input_qtd_palavras') else int(request.POST.get(u'input_qtd_palavras')),
              "numero_gram" : int(request.POST.get(u'numero_gram', 0)),
              "abrangencia": abrangencia,
              "palavras_chave": palavras_chave,
              "limpar_caracteres": bool(int(request.POST.get("checkbox_limparcaracteres", False))),
              "eliminar_pontuacao":bool(int(request.POST.get("checkbox_eliminarpontuacao", False))),
              "eliminar_stopwords": bool(int(request.POST.get("checkbox_eliminarstopwords", False)))}

    if abrangencia == "web":
        crawler_facade = cf.get_news_crawler()
    else:
        crawler_facade = cf.get_twitter_crawler()
        configuracoes = {}
        erros = {}
        try:
            configuracoes = ler_dados_acesso_twitter_arquivo(arquivo_conf_twitter, request.user.email)
            crawler_facade.validar_credenciais_twitter(configuracoes)
        except TweepError as e:
            erros = {"erros": ["Não foi possível se contectar ao twitter usando as credenciais informadas"]}
        except Exception as e:
            erros = {"erros":(str(e),)}

        if "erros" in erros:
            return render(request, "WebCrawlerEngine/index.html", erros)

        opcoes.update(configuracoes)
        crawler_facade.iniciar_twitter_crawler(opcoes)

        return redirect('WebCrawler:processamento', permanent=True)

    opcao_coleta_selecionada = request.POST.get(u'fonte_coleta')

    dominios = []
    urls_usuario = []

    if opcao_coleta_selecionada == "palavras_chave":

        # É preciso que o usuário tenha informado pelo menos uma palavra chave
        if not palavras_chave:
            # Exibir mensagem de erro e mandar renderizar
            return render(request, 'WebCrawlerEngine/index.html', {"user": request.user})
        crawler_facade.iniciar_web_crawler_com_palavras_chave(**opcoes)
        return redirect('WebCrawler:processamento', permanent=True)

    if opcao_coleta_selecionada == "urls_sementes":
        # É preciso haver, nesse caso, pelo menos um domínio selecionado
        dominios = get_dominios_selecionados(request.POST.getlist(u"slc_dominios[]", []))

    elif opcao_coleta_selecionada == "palavras_chave":
        palavras_chave = request.POST.get(u'text_palavras_chave', "").split(",")
        # É preciso que o usuário tenha informado pelo menos uma palavra chave
        if not palavras_chave:
            # Exibir mensagem de erro e mandar renderizar
            return render(request, 'WebCrawlerEngine/index.html', {"user": request.user})

    elif opcao_coleta_selecionada == "arquivo_urls":
        arquivo_urls = request.FILES.get(u'coleta_arquivo_file')
        try:
            urls_usuario = ler_urls_arquivo(arquivo_urls, request.user.email)
        except Exception as e:
            return render(request, 'WebCrawlerEngine/index.html', {"user": request.user, "erros": (str(e),)})

    crawler_facade.iniciar_web_crawler_com_urls_sementes(urls_usuario= urls_usuario, dominios= dominios, **opcoes)

    return redirect('WebCrawler:processamento', permanent=True)

WebCrawler/WebCrawlerEngine/templates/WebCrawlerEngine/editar_dados_usuario.html
{% extends "WebCrawlerEngine/template.html" %}

{% block title %}
Web Crawler - Processing
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">Enter the new data</div>
            <div class="panel-body">
                <form action="{% url 'editar_dados_usuario' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label" for="nome">Name</label>
                        <label style="color:red;">*</label>
                        <input type="text" class="form-control" id="nome" name="nome" value="{{user.first_name}}" >
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="sobrenome">Last name</label>
                        <label style="color:red;">*</label>
                        <input type="text" class="form-control" id="sobrenome" name="sobrenome" value="{{user.last_name}}">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" value="{{user.email}}" readonly>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="senha">New password</label>
                        <input type="password" class="form-control" id="senha" name="senha">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="confirmacao_senha">Confirm new password</label>
                        <input type="password" class="form-control" id="confirmacao_senha" name="confirmacao_senha">
                    </div>
                    {% if erro %}
                    <p style="font-size:90%; color: red;"> {{erro}}</p>
                    {%elif info %}
                    <p style="font-size:90%;font-weight: bold;"> {{info}}</p>
                    {% endif %}
                    <div class="row" style="text-align: center;">
                        <button type="submit" class="btn btn-default">Salvar</button>
                        <a href="{% url 'WebCrawler:index' %}" class="btn btn-default">
                            Return
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>

{% endblock %}

WebCrawler/WebCrawlerEngine/templates/WebCrawlerEngine/erro_alert.html
{% if erros %}
    <center>
        <div class="alert alert-danger" style="width: 60%;margin-top:-30px">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Error:</strong>
            {% for erro in erros %}
                {{erro}}
                <br/>
            {% endfor %}
        </div>
    </center>
{% endif %}

WebCrawler/WebCrawlerEngine/templates/WebCrawlerEngine/index.html
{% extends "WebCrawlerEngine/template.html" %}


{% block title %}
Web Crawler
{% endblock %}

{% block content %}

{% include "WebCrawlerEngine/erro_alert.html" %}

{% include "WebCrawlerEngine/index/abas_navegacao.html" %}

<form action="{% url 'WebCrawler:iniciar' %}" method="post" enctype="multipart/form-data" id="frmPrincipal">
    <div class="tab-content">
        {% csrf_token %}
        {% include "WebCrawlerEngine/index/aba_crawler.html"%}
        {% include "WebCrawlerEngine/index/aba_modelo_linguagem.html"%}
        {% include "WebCrawlerEngine/index/aba_entidades_nomeadas.html"%}
        {% include "WebCrawlerEngine/index/aba_limpeza_corpus.html"%}
        {% include "WebCrawlerEngine/index/aba_geracao.html"%}
    </div>
</form>

{% endblock %}

WebCrawler/WebCrawlerEngine/templates/WebCrawlerEngine/login.html
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css'>
    <link rel="stylesheet" href="/static/css/style_login.css">
</head>

<body>

<div class="wrapper">
    <form class="form-signin" method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <h2 class="form-signin-heading">Login</h2>
        <input type="text" class="form-control" id="email"
               maxlength="254" name="email" placeholder="Email" required=""
               autofocus="true" />
        <input type="password" class="form-control" id="senha"
               name="senha"
               placeholder="Password" required=""/>
        {% if erro %}
            <p style="font-size:90%; color: red;"> {{erro}}</p>
        {%elif info %}
            <p style="font-size:90%;font-weight: bold;"> {{info}}</p>
        {% endif %}

        <input type='hidden' name='next' value='{{next}}' />
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
        <br/>
        <div style="text-align: center;">
            <a href="{% url 'novo_usuario' %}">Register</a>
        </div>
    </form>
</div>
</body>
</html>

WebCrawler/WebCrawlerEngine/templates/WebCrawlerEngine/novo_usuario.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <!--<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">-->
    <title>Web Crawler</title>
    <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css'>
</head>
<body>
<div class="container" style="margin-top: 40px">
    <div class="row">
        <h1> Cadastrar novo usuário</h1>
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">Enter your details</div>
                <div class="panel-body">
                    <form action="{% url 'cadastrar_novo_usuario' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label" for="nome">Name</label>
                            <label style="color:red;">*</label>
                            <input type="text" class="form-control" id="nome" name="nome" >
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="sobrenome">Surname</label>
                            <label style="color:red;">*</label>
                            <input type="text" class="form-control" id="sobrenome" name="sobrenome" >
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="email">Email</label>
                            <label style="color:red;">*</label>
                            <input type="email" class="form-control" id="email" name="email">
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="senha">Password</label>
                            <label style="color:red;">*</label>
                            <input type="password" class="form-control" id="senha" name="senha">
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="confirmacao_senha">Confirm your password</label>
                            <label style="color:red;">*</label>
                            <input type="password" class="form-control" id="confirmacao_senha" name="confirmacao_senha">
                        </div>
                        {% if erro %}
                        <p style="font-size:90%; color: red;"> {{erro}}</p>
                        {%elif info %}
                        <p style="font-size:90%;"> {{info}}</p>
                        {% endif %}
                        <button type="submit" class="btn btn-default">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

WebCrawler/WebCrawlerEngine/templates/WebCrawlerEngine/processamento.html
{% extends "WebCrawlerEngine/template.html" %}


{% block title %}
Web Crawler - Processamento
{% endblock %}

{% block content %}
<form action="{% url 'WebCrawler:processamento' %}" method="post">
    {%if processamento_em_execucao %}
        <script>
            setTimeout(function() {window.location=window.location;},1000);
        </script>
    {% endif %}

    <div class="panel panel-primary" style="margin-left:10px;margin-right:10px">
        <div class="panel-heading" style="text-align: center;">
            <h3 class="panel-title">Processing info</h3>
        </div>
        <div class="panel-body">
             <table class="table table-bordered table-condensed" style="margin=">
                <tr style="font-weight:bold;text-align: center">
                    <td>
                       Status
                    </td>
                    <td>
                       Palavras
                    </td>
                    <td>
                        {% if abrangencia == "web" %}
                            Page
                        {% else %}
                            Twittes
                        {% endif %}
                    </td>
                    <td>
                        Execution time
                    </td>
                    <td>
                        Action
                    </td>
                </tr>
                <tr style="text-align: center">
                    <td>
                        {% if processamento_em_execucao %}
                            {{status_processamento}} <i class="fa fa-spinner fa-spin"></i>
                        {% elif status_processamento == "Finalizado" %}
                            Finished <i class="fa fa-check"></i>
                        {% else %}
                            Stoped <i class="fa fa-meh-o"></i>
                        {% endif %}
                    </td>
                     <td>
                         {%if status_processamento != "Parado" %}
                            {{contagem_palavras}}
                        {% else %}
                            --
                        {% endif %}
                    </td>

                     <td>
                        {% if status_processamento != "Parado" and  abrangencia == "web"%}
                            {{contagem_paginas}}
                        {% elif status_processamento != "Parado" and  abrangencia == "twitter" %}
                            {{contagem_twittes}}
                         {% else %}
                            --
                        {% endif %}
                    </td>

                    <td>
                        {%if status_processamento != "Parado" %}
                            {{tempo_execucao}}
                        {% else %}
                            --
                        {% endif %}
                    </td>
                    <td >
                         {%if status_processamento == "Baixando corpus" %}
                            <div class="span8">
                                <a href="{% url 'WebCrawler:parar_processamento' %}"> <i class="fa fa-stop" style="color:black" title="Stop"></i></a>
                            </div>
                        {% elif status_processamento == "Finalizado" %}
                            <div class="span8">
                                 <a href="{% url 'WebCrawler:download_corpora' %}"> <i class="fa fa-download" style="color:black"  title="Download"></i></a>
                            </div>
                        {% elif  status_processamento == "Processando corpus"%}
                            Please, wait a minute...
                        {% else %}
                            --
                        {% endif %}
                    </td>
                </tr>
            </table>

             {%if status_processamento != "Finalizado" and status_processamento != "Parado" %}
                When the current processing end, you can make a new search.
             {%endif %}

        </div>

    </div>
</form>
{% endblock %}

WebCrawler/WebCrawlerEngine/templates/WebCrawlerEngine/template.html
<!DOCTYPE html>
<html>
<head lang="pt-br">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <!--<link href="/static/css/bootstrap-rtl.css" rel="stylesheet"/>-->
    <!--<link href="/static/css/bootstrap-rtl.min.css" rel="stylesheet"/>-->
    <!--<link href="/static/css/bootstrap.css" rel="stylesheet"/>-->
    <link href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <link href="/static/css/timeline.css" rel="stylesheet">
    <link href="/static/css/sb-admin-2.css" rel="stylesheet">
    <link href="/static/bower_components/morrisjs/morris.css" rel="stylesheet">
    <link href="/static/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/estilo.css" rel="stylesheet"/>
    <link href="/static/lou-multi-select/css/multi-select.css" media="screen" rel="stylesheet" type="text/css">

    <script src="/static/bower_components/jquery/dist/jquery.js"></script>
    <!--<script src="/static/lou-multi-select/js/jquery.js"></script>-->
    <script src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/static/bower_components/metisMenu/dist/metisMenu.min.js"></script>
    <script src="/static/script/sb-admin-2.js"></script>
    <script src="/static/script/script.js"></script>
    <script src="/static/script/bootstrap-filestyle.js"></script>

</head>
<body>

<!--<div class="panel-body">-->
    <div id="interface" style="width: 80%" class="content">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'WebCrawler:index' %}"><p><img height="40px" width="35px" src="/static/imagem/ufs_logo.png"/> Web Crawler</p></a>
            </div>

            <!-- Ícones da barra superior-->
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="{% url 'WebCrawler:index' %}">
                        <i class="fa fa-home fa-fw"></i><label style="font-size: 11pt; padding-left: 2px;"> Home</label>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-users fa-fw"></i><label style="font-size: 11pt; padding-left: 2px;"> About us</label>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-info fa-fw"></i><label style="font-size: 11pt; padding-left: 2px;"> Documentation</label>
                    </a>
                </li>
                {% if corpus_gerado %}
                    <li>
                        <a href="{% url 'WebCrawler:processamento' %}">
                            <i class="fa fa-thumbs-o-up" title="Corpora disponível para download"></i><label style="font-size: 11pt; padding-left: 2px;"> Corpora </label>
                        </a>
                    </li>
                {% endif %}
                   <li>
                    <a  href="{% url 'editar_dados_usuario' %}">
                        <i class="fa fa-user" title="Editar meus dados"></i><label style="font-size: 11pt; padding-left: 2px;"> Personal info </label>
                    </a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">
                        ({{user.first_name}})
                        <i class="fa fa-sign-out" ></i><label style="font-size: 11pt; padding-left: 2px;" > Log out </label>
                    </a>
                </li>

            </ul>
        </nav>
        <br/> <br/>
        {% block content %}
        {% endblock %}
    </div>
<!--</div>-->

<script>$(document).ready(function() {
                $(":file").filestyle('buttonText', 'Select file');
                $(":file").filestyle({disabled: true});
            });</script>
<script>
        $("#radio_urls_sementes").click(function(){
            $(":file").filestyle('disabled', true);
            tratarFonteColetaUrlsSementes();
        });
        $("#radio_coleta_arquivo").click(function(){
            $("#coleta_select_file").filestyle('disabled', false);
            desabilitaLabel();
        });
        $("#radio_abrangencia_twitter").click(function(){
            $("#arquivo_dados_acesso_twitter").filestyle('disabled', false);
            desabilitaLabel();
        });
        $("#radio_palavras_chave").click(function(){
            $(":file").filestyle('disabled', true);
            desabilitaLabel();
        });
        $(".dominio_checkboxes").click(function(){
            var someonechecked = 0;
            for(var i = 0; i < document.getElementsByClassName("dominio_checkboxes").length; i++){
            if (document.getElementsByClassName("dominio_checkboxes")[i].checked == true){
                someonechecked = 1;
                break;
            }
            }
            if (someonechecked === 0)
                habilitaLabel();
            else
                desabilitaLabel();
        });
    </script>
</body>
</html>